# -*- coding: utf-8 -*-
"""2.1.multiclass.nn.pytorch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i99CeKV9h_SqsC_vO4bN5bZw-YVot8Wf
"""

import torch
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
import torch.nn as nn

num_classes = 4
num_features = 2
random_seed = 42

# create multi-class data
x_blob, y_blob = make_blobs(n_samples = 1000,
                            n_features  = num_features,
                            centers = num_classes,
                            cluster_std = 1.5,
                            random_state = random_seed)


# turn data into tensors
x_blob = torch.from_numpy(x_blob).type(torch.float)
y_blob = torch.from_numpy(y_blob).type(torch.float)



# split into train and test
x_blob_train, x_blob_test, y_blob_train, y_blob_test = train_test_split(x_blob,
                                                                        y_blob,
                                                                        test_size = 0.2,
                                                                        random_state = random_seed)
# vizualize
plt.figure(figsize=(10, 7))
plt.scatter(x_blob[:, 0], x_blob[:, 1], c=y_blob, cmap=plt.cm.RdYlBu);

# Create device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# building a multi-class classification model

class BlobModel(nn.Module):
  def __init__(self, input_features, output_features, hidden_units=8):
    super().__init__()
    self.linear_layer_stack = nn.Sequential(
        nn.Linear(in_features = input_features, out_features = hidden_units),
        nn.ReLU(),
        nn.Linear(in_features = hidden_units, out_features = hidden_units),
        nn.ReLU(),
        nn.Linear(in_features = hidden_units, out_features = output_features)
    )


  def forward(self, x):
    return self.linear_layer_stack(x)

model_0 = BlobModel(input_features=2,
                    output_features=4,
                    hidden_units=8).to(device)

# create a loss fn
loss_fn = nn.CrossEntropyLoss()

# create an optimizer
optimizer = torch.optim.SGD(params= model_0.parameters(),
                            lr = 0.1)

def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct / len(y_pred)) * 100
    return acc

model_0.eval()
with torch.inference_mode():
  y_logits = model_0(x_blob_test)


y_logits[:10]

y_blob_test[:10]

y_pred_prob = torch.softmax(y_logits, dim = 1)
print(y_logits[:5])
print(y_pred_prob[:5])

torch.sum(y_pred_prob[0])

torch.max(y_pred_prob[0])

y_blob_train = y_blob_train.type(torch.LongTensor)
y_blob_test = y_blob_test.type(torch.LongTensor)

y_pred = torch.argmax(y_pred_prob, dim=1)
y_pred
#y_pred = torch.argmax(y_pred_prob, dim=1) means choosing the class index with the highest probability predicted by the model for each sample (row).

print(y_pred_prob[0])
print(torch.argmax(y_pred_prob[0]))

print(x_blob_test.shape)
print(y_blob_test.shape)

test_logits = model_0(x_blob_test)
test_pred = torch.softmax(test_logits, dim=1).argmax(dim=1)
test_loss = loss_fn(test_logits, y_blob_test)
test_acc = accuracy_fn(y_true=y_blob_test, y_pred=test_pred)

# Fit the model
torch.manual_seed(42)

epochs = 100

x_blob_train, y_blob_train = x_blob_train.to(device), y_blob_train.to(device)
x_blob_test, y_blob_test = x_blob_test.to(device), y_blob_test.to(device)

for epoch in range(epochs):
    model_0.train()

    y_logits = model_0(x_blob_train)
    y_pred = torch.softmax(y_logits, dim=1).argmax(dim=1)
    loss = loss_fn(y_logits, y_blob_train)
    acc = accuracy_fn(y_true=y_blob_train,
                      y_pred=y_pred)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Testing
    model_0.eval()
    with torch.inference_mode():
      test_logits = model_0(x_blob_test)
      test_pred = torch.softmax(test_logits, dim=1).argmax(dim=1)

      test_loss = loss_fn(test_logits, y_blob_test)
      test_acc = accuracy_fn(y_true=y_blob_test,
                             y_pred=test_pred)


    if epoch % 10 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.5f}, Acc: {acc:.2f}% | Test Loss: {test_loss:.5f}, Test Acc: {test_acc:.2f}%")

# Make predictions
model_0.eval()
with torch.inference_mode():
    y_logits = model_0(x_blob_test)

# View the first 10 predictions
y_logits[:10]

y_pred_probs = torch.softmax(y_logits, dim=1)
y_preds = y_pred_probs.argmax(dim=1)

print(f"Predictions: {y_preds[:10]}\nLabels: {y_blob_test[:10]}")
print(f"Test accuracy: {accuracy_fn(y_true=y_blob_test, y_pred=y_preds)}%")

import torch
import numpy as np
import matplotlib.pyplot as plt

def plot_decision_boundary(model, X, y):


    model.to("cpu")
    X, y = X.to("cpu"), y.to("cpu")

    x_min, x_max = X[:, 0].min() - 0.1, X[:, 0].max() + 0.1
    y_min, y_max = X[:, 1].min() - 0.1, X[:, 1].max() + 0.1

    xx, yy = np.meshgrid(
        np.linspace(x_min, x_max, 101),
        np.linspace(y_min, y_max, 101)
    )

    X_to_pred = torch.from_numpy(
        np.column_stack((xx.ravel(), yy.ravel()))
    ).float()

    model.eval()
    with torch.inference_mode():
        y_logits = model(X_to_pred)

        if len(torch.unique(y)) > 2:
            y_pred = torch.softmax(y_logits, dim=1).argmax(dim=1)
        else:
            y_pred = torch.round(torch.sigmoid(y_logits))

    y_pred = y_pred.reshape(xx.shape).detach().numpy()

    plt.contourf(xx, yy, y_pred, cmap=plt.cm.RdYlBu, alpha=0.7)
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap=plt.cm.RdYlBu, s=40)
    plt.xlim(xx.min(), xx.max())
    plt.ylim(yy.min(), yy.max())

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Train")
plot_decision_boundary(model_0, x_blob_train, y_blob_train)
plt.subplot(1, 2, 2)
plt.title("Test")
plot_decision_boundary(model_0, x_blob_test, y_blob_test)

try:
    from torchmetrics import Accuracy
except:
    !pip install torchmetrics==0.9.3
    from torchmetrics import Accuracy


torchmetrics_accuracy = Accuracy(task='multiclass', num_classes=4).to(device)


torchmetrics_accuracy(y_preds, y_blob_test)















#əlavə


import numpy as np
N = 100
D = 2
K = 3
X = np.zeros((N*K,D))
y = np.zeros(N*K, dtype='uint8')
for j in range(K):
  ix = range(N*j,N*(j+1))
  r = np.linspace(0.0,1,N)
  t = np.linspace(j*4,(j+1)*4,N) + np.random.randn(N)*0.2
  X[ix] = np.c_[r*np.sin(t), r*np.cos(t)]
  y[ix] = j

plt.scatter(X[:, 0], X[:, 1], c=y, s=40, cmap=plt.cm.Spectral)
plt.show()